version: '3.8'

services:
  config_server:
    env_file:
      - "../.env"
    build:
      context: .
    container_name: config_server
    restart: always
    ports:
      - "8888:8080"
    environment:
      SERVICE_PORT: 8888

